modLoader = "javafml"
license = "MIT"
issueTrackerURL = "https://github.com/i5wear/HUD-Manager/issues"

[[mods]]
modId = "hudmanager"
version = "${version}"
displayName = "HUD Manager"
description = '''Manages HUD elements gracefully.'''
authors = "i5wear"
credits = "Ferinjoque"
displayURL = "https://modrinth.com/mod/HUD-Manager"
logoFile = "assets/hudmanager/icon.png"

[[mixins]]
config = "hudmanager.mixins.json"

[[dependencies.hudmanager]]
modId = "minecraft"
versionRange = "[1.21.11,)"

[[dependencies.hudmanager]]
modId = "neoforge"
versionRange = "[21.11,)"