modLoader="javafml"
loaderVersion = "[1, )"
license = "MIT"

[[mods]]
modId = "hudmanager"
version = "${version}"
displayName = "HUD Manager"
displayURL = "https://modrinth.com/mod/HUD-Manager"
authors = "i5wear"
description = '''Manages HUD elements gracefully.'''
logoFile = "assets/hudmanager/icon.png"

[[dependencies.hudmanager]]
modId = "neoforge"
versionRange = "[21.3, 21.6)"

[[dependencies.hudmanager]]
modId = "minecraft"
versionRange = "[1.21.3, 1.21.6)"

[[mixins]]
config = "hudmanager.mixins.json"
