modLoader="javafml"
issueTrackerURL = "https://github.com/i5wear/HUD-Manager/issues"
license = "MIT"

[[mods]]
modId = "hudmanager"
version = "${version}"
displayName = "HUD Manager"
displayURL = "https://modrinth.com/mod/HUD-Manager"
authors = "i5wear"
description = '''Manages HUD elements gracefully.'''
logoFile = "assets/hudmanager/icon.png"

[[dependencies.hudmanager]]
modId = "neoforge"
versionRange = "[21.7, 21.11)"

[[dependencies.hudmanager]]
modId = "minecraft"
versionRange = "[1.21.7, 1.21.11)"

[[mixins]]
config = "hudmanager.mixins.json"
